# Generated by Django 4.2.7 on 2023-12-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='profile',
        ),
    ]
