# Generated by Django 4.2.7 on 2023-12-19 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_city_item_country_item_more_item_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_info',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Yaroqsiz telefon raqam!', regex='^\\+998\\d{9}$')]),
        ),
    ]
