# Generated by Django 4.2.7 on 2023-12-26 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_newsletter_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_info',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Yaroqsiz telefon raqam!', regex='^\\+998\\d{9}$')]),
        ),
    ]
