# Generated by Django 4.2.7 on 2023-12-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/logo.jpg', null=True, upload_to='images/'),
        ),
    ]
