# Generated by Django 4.2.7 on 2023-12-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='primary_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown - Tan', 'Brown Tan'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Maroon', 'Maron'), ('Orange', 'Orange'), ('Peach', 'Peach'), ('Pink', 'Pink'), ('Platinum', 'Platinum'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='secondary_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown - Tan', 'Brown Tan'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Maroon', 'Maron'), ('Orange', 'Orange'), ('Peach', 'Peach'), ('Pink', 'Pink'), ('Platinum', 'Platinum'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
